namespace CAT.AID.Web.Services.PDF
{
    public abstract class BasePdfTemplate : IDocument
    {
        protected BasePdfTemplate(string title, string logoLeft, string logoRight)
        {
            Title = title;
            LogoLeft = logoLeft;
            LogoRight = logoRight;
        }

        protected string Title { get; }
        protected string LogoLeft { get; }
        protected string LogoRight { get; }

        public void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                page.Margin(30);

                page.Header().Element(Header);
                page.Content().Element(ComposeContent);
                page.Footer().AlignCenter().Text(x =>
                {
                    x.Span("Generated by CAT.AID").FontSize(9);
                });
            });
        }

        protected abstract void ComposeContent(IContainer container);

        protected virtual void Header(IContainer container)
        {
            container.Row(row =>
            {
                row.ConstantItem(80).Image(LogoLeft);
                row.RelativeItem().AlignCenter().Text(Title).Bold().FontSize(16);
                row.ConstantItem(80).Image(LogoRight);
            });
        }
    }
}
